---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-circleci-meowhq-dev-v1-context
  failurePolicy: Fail
  name: mcontext.kb.io
  rules:
  - apiGroups:
    - circleci.meowhq.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - contexts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-circleci-meowhq-dev-v1-provider
  failurePolicy: Fail
  name: mprovider.kb.io
  rules:
  - apiGroups:
    - circleci.meowhq.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - providers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-circleci-meowhq-dev-v1-context
  failurePolicy: Fail
  name: vcontext.kb.io
  rules:
  - apiGroups:
    - circleci.meowhq.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - contexts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-circleci-meowhq-dev-v1-provider
  failurePolicy: Fail
  name: vprovider.kb.io
  rules:
  - apiGroups:
    - circleci.meowhq.dev
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - providers
  sideEffects: None
