# permissions for end users to edit providers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: provider-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: circleci-operator
    app.kubernetes.io/part-of: circleci-operator
    app.kubernetes.io/managed-by: kustomize
  name: provider-editor-role
rules:
- apiGroups:
  - circleci.meowhq.dev
  resources:
  - providers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - circleci.meowhq.dev
  resources:
  - providers/status
  verbs:
  - get
