/*
CircleCI API

This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package circleci

import (
	"encoding/json"
)

// checks if the GetWebhooks200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetWebhooks200Response{}

// GetWebhooks200Response A list of webhooks
type GetWebhooks200Response struct {
	Items []Webhook `json:"items"`
	// A token to pass as a `page-token` query parameter to return the next page of results.
	NextPageToken string `json:"next_page_token"`
}

// NewGetWebhooks200Response instantiates a new GetWebhooks200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetWebhooks200Response(items []Webhook, nextPageToken string) *GetWebhooks200Response {
	this := GetWebhooks200Response{}
	this.Items = items
	this.NextPageToken = nextPageToken
	return &this
}

// NewGetWebhooks200ResponseWithDefaults instantiates a new GetWebhooks200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetWebhooks200ResponseWithDefaults() *GetWebhooks200Response {
	this := GetWebhooks200Response{}
	return &this
}

// GetItems returns the Items field value
func (o *GetWebhooks200Response) GetItems() []Webhook {
	if o == nil {
		var ret []Webhook
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *GetWebhooks200Response) GetItemsOk() ([]Webhook, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *GetWebhooks200Response) SetItems(v []Webhook) {
	o.Items = v
}

// GetNextPageToken returns the NextPageToken field value
func (o *GetWebhooks200Response) GetNextPageToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value
// and a boolean to check if the value has been set.
func (o *GetWebhooks200Response) GetNextPageTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextPageToken, true
}

// SetNextPageToken sets field value
func (o *GetWebhooks200Response) SetNextPageToken(v string) {
	o.NextPageToken = v
}

func (o GetWebhooks200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetWebhooks200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["next_page_token"] = o.NextPageToken
	return toSerialize, nil
}

type NullableGetWebhooks200Response struct {
	value *GetWebhooks200Response
	isSet bool
}

func (v NullableGetWebhooks200Response) Get() *GetWebhooks200Response {
	return v.value
}

func (v *NullableGetWebhooks200Response) Set(val *GetWebhooks200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetWebhooks200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetWebhooks200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetWebhooks200Response(val *GetWebhooks200Response) *NullableGetWebhooks200Response {
	return &NullableGetWebhooks200Response{value: val, isSet: true}
}

func (v NullableGetWebhooks200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetWebhooks200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
