/*
CircleCI API

This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package circleci

import (
	"encoding/json"
)

// checks if the CreateContextRequestOwnerOneOf1 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateContextRequestOwnerOneOf1{}

// CreateContextRequestOwnerOneOf1 struct for CreateContextRequestOwnerOneOf1
type CreateContextRequestOwnerOneOf1 struct {
	// A string that represents an organization. Specify either this or id. Cannot be used for accounts.
	Slug string `json:"slug"`
	// The type of owner. Defaults to \"organization\". Accounts are only used as context owners in server and must be specified by an id instead of a slug.
	Type *string `json:"type,omitempty"`
}

// NewCreateContextRequestOwnerOneOf1 instantiates a new CreateContextRequestOwnerOneOf1 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateContextRequestOwnerOneOf1(slug string) *CreateContextRequestOwnerOneOf1 {
	this := CreateContextRequestOwnerOneOf1{}
	this.Slug = slug
	return &this
}

// NewCreateContextRequestOwnerOneOf1WithDefaults instantiates a new CreateContextRequestOwnerOneOf1 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateContextRequestOwnerOneOf1WithDefaults() *CreateContextRequestOwnerOneOf1 {
	this := CreateContextRequestOwnerOneOf1{}
	return &this
}

// GetSlug returns the Slug field value
func (o *CreateContextRequestOwnerOneOf1) GetSlug() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Slug
}

// GetSlugOk returns a tuple with the Slug field value
// and a boolean to check if the value has been set.
func (o *CreateContextRequestOwnerOneOf1) GetSlugOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Slug, true
}

// SetSlug sets field value
func (o *CreateContextRequestOwnerOneOf1) SetSlug(v string) {
	o.Slug = v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateContextRequestOwnerOneOf1) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateContextRequestOwnerOneOf1) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateContextRequestOwnerOneOf1) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreateContextRequestOwnerOneOf1) SetType(v string) {
	o.Type = &v
}

func (o CreateContextRequestOwnerOneOf1) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateContextRequestOwnerOneOf1) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["slug"] = o.Slug
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableCreateContextRequestOwnerOneOf1 struct {
	value *CreateContextRequestOwnerOneOf1
	isSet bool
}

func (v NullableCreateContextRequestOwnerOneOf1) Get() *CreateContextRequestOwnerOneOf1 {
	return v.value
}

func (v *NullableCreateContextRequestOwnerOneOf1) Set(val *CreateContextRequestOwnerOneOf1) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateContextRequestOwnerOneOf1) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateContextRequestOwnerOneOf1) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateContextRequestOwnerOneOf1(val *CreateContextRequestOwnerOneOf1) *NullableCreateContextRequestOwnerOneOf1 {
	return &NullableCreateContextRequestOwnerOneOf1{value: val, isSet: true}
}

func (v NullableCreateContextRequestOwnerOneOf1) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateContextRequestOwnerOneOf1) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
