/*
CircleCI API

This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package circleci

import (
	"encoding/json"
)

// checks if the ListContexts200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListContexts200Response{}

// ListContexts200Response struct for ListContexts200Response
type ListContexts200Response struct {
	Items []Context `json:"items"`
	// A token to pass as a `page-token` query parameter to return the next page of results.
	NextPageToken string `json:"next_page_token"`
}

// NewListContexts200Response instantiates a new ListContexts200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListContexts200Response(items []Context, nextPageToken string) *ListContexts200Response {
	this := ListContexts200Response{}
	this.Items = items
	this.NextPageToken = nextPageToken
	return &this
}

// NewListContexts200ResponseWithDefaults instantiates a new ListContexts200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListContexts200ResponseWithDefaults() *ListContexts200Response {
	this := ListContexts200Response{}
	return &this
}

// GetItems returns the Items field value
func (o *ListContexts200Response) GetItems() []Context {
	if o == nil {
		var ret []Context
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ListContexts200Response) GetItemsOk() ([]Context, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ListContexts200Response) SetItems(v []Context) {
	o.Items = v
}

// GetNextPageToken returns the NextPageToken field value
func (o *ListContexts200Response) GetNextPageToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value
// and a boolean to check if the value has been set.
func (o *ListContexts200Response) GetNextPageTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextPageToken, true
}

// SetNextPageToken sets field value
func (o *ListContexts200Response) SetNextPageToken(v string) {
	o.NextPageToken = v
}

func (o ListContexts200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListContexts200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["next_page_token"] = o.NextPageToken
	return toSerialize, nil
}

type NullableListContexts200Response struct {
	value *ListContexts200Response
	isSet bool
}

func (v NullableListContexts200Response) Get() *ListContexts200Response {
	return v.value
}

func (v *NullableListContexts200Response) Set(val *ListContexts200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListContexts200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListContexts200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListContexts200Response(val *ListContexts200Response) *NullableListContexts200Response {
	return &NullableListContexts200Response{value: val, isSet: true}
}

func (v NullableListContexts200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListContexts200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
