/*
CircleCI API

This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package circleci

import (
	"encoding/json"
)

// checks if the ListContextsDefaultResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListContextsDefaultResponse{}

// ListContextsDefaultResponse struct for ListContextsDefaultResponse
type ListContextsDefaultResponse struct {
	Message *string `json:"message,omitempty"`
}

// NewListContextsDefaultResponse instantiates a new ListContextsDefaultResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListContextsDefaultResponse() *ListContextsDefaultResponse {
	this := ListContextsDefaultResponse{}
	return &this
}

// NewListContextsDefaultResponseWithDefaults instantiates a new ListContextsDefaultResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListContextsDefaultResponseWithDefaults() *ListContextsDefaultResponse {
	this := ListContextsDefaultResponse{}
	return &this
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *ListContextsDefaultResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ListContextsDefaultResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *ListContextsDefaultResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *ListContextsDefaultResponse) SetMessage(v string) {
	o.Message = &v
}

func (o ListContextsDefaultResponse) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListContextsDefaultResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableListContextsDefaultResponse struct {
	value *ListContextsDefaultResponse
	isSet bool
}

func (v NullableListContextsDefaultResponse) Get() *ListContextsDefaultResponse {
	return v.value
}

func (v *NullableListContextsDefaultResponse) Set(val *ListContextsDefaultResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableListContextsDefaultResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableListContextsDefaultResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListContextsDefaultResponse(val *ListContextsDefaultResponse) *NullableListContextsDefaultResponse {
	return &NullableListContextsDefaultResponse{value: val, isSet: true}
}

func (v NullableListContextsDefaultResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListContextsDefaultResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
