/*
CircleCI API

This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package circleci

import (
	"encoding/json"
)

// checks if the ListEnvironmentVariablesFromContext200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListEnvironmentVariablesFromContext200Response{}

// ListEnvironmentVariablesFromContext200Response struct for ListEnvironmentVariablesFromContext200Response
type ListEnvironmentVariablesFromContext200Response struct {
	Items []ListEnvironmentVariablesFromContext200ResponseItemsInner `json:"items"`
	// A token to pass as a `page-token` query parameter to return the next page of results.
	NextPageToken string `json:"next_page_token"`
}

// NewListEnvironmentVariablesFromContext200Response instantiates a new ListEnvironmentVariablesFromContext200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListEnvironmentVariablesFromContext200Response(items []ListEnvironmentVariablesFromContext200ResponseItemsInner, nextPageToken string) *ListEnvironmentVariablesFromContext200Response {
	this := ListEnvironmentVariablesFromContext200Response{}
	this.Items = items
	this.NextPageToken = nextPageToken
	return &this
}

// NewListEnvironmentVariablesFromContext200ResponseWithDefaults instantiates a new ListEnvironmentVariablesFromContext200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListEnvironmentVariablesFromContext200ResponseWithDefaults() *ListEnvironmentVariablesFromContext200Response {
	this := ListEnvironmentVariablesFromContext200Response{}
	return &this
}

// GetItems returns the Items field value
func (o *ListEnvironmentVariablesFromContext200Response) GetItems() []ListEnvironmentVariablesFromContext200ResponseItemsInner {
	if o == nil {
		var ret []ListEnvironmentVariablesFromContext200ResponseItemsInner
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *ListEnvironmentVariablesFromContext200Response) GetItemsOk() ([]ListEnvironmentVariablesFromContext200ResponseItemsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *ListEnvironmentVariablesFromContext200Response) SetItems(v []ListEnvironmentVariablesFromContext200ResponseItemsInner) {
	o.Items = v
}

// GetNextPageToken returns the NextPageToken field value
func (o *ListEnvironmentVariablesFromContext200Response) GetNextPageToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value
// and a boolean to check if the value has been set.
func (o *ListEnvironmentVariablesFromContext200Response) GetNextPageTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextPageToken, true
}

// SetNextPageToken sets field value
func (o *ListEnvironmentVariablesFromContext200Response) SetNextPageToken(v string) {
	o.NextPageToken = v
}

func (o ListEnvironmentVariablesFromContext200Response) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListEnvironmentVariablesFromContext200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["items"] = o.Items
	toSerialize["next_page_token"] = o.NextPageToken
	return toSerialize, nil
}

type NullableListEnvironmentVariablesFromContext200Response struct {
	value *ListEnvironmentVariablesFromContext200Response
	isSet bool
}

func (v NullableListEnvironmentVariablesFromContext200Response) Get() *ListEnvironmentVariablesFromContext200Response {
	return v.value
}

func (v *NullableListEnvironmentVariablesFromContext200Response) Set(val *ListEnvironmentVariablesFromContext200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableListEnvironmentVariablesFromContext200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableListEnvironmentVariablesFromContext200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListEnvironmentVariablesFromContext200Response(val *ListEnvironmentVariablesFromContext200Response) *NullableListEnvironmentVariablesFromContext200Response {
	return &NullableListEnvironmentVariablesFromContext200Response{value: val, isSet: true}
}

func (v NullableListEnvironmentVariablesFromContext200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListEnvironmentVariablesFromContext200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
