/*
CircleCI API

This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package circleci

import (
	"encoding/json"
)

// checks if the CheckoutKeyInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CheckoutKeyInput{}

// CheckoutKeyInput struct for CheckoutKeyInput
type CheckoutKeyInput struct {
	// The type of checkout key to create. This may be either `deploy-key` or `user-key`.
	Type string `json:"type"`
}

// NewCheckoutKeyInput instantiates a new CheckoutKeyInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCheckoutKeyInput(type_ string) *CheckoutKeyInput {
	this := CheckoutKeyInput{}
	this.Type = type_
	return &this
}

// NewCheckoutKeyInputWithDefaults instantiates a new CheckoutKeyInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCheckoutKeyInputWithDefaults() *CheckoutKeyInput {
	this := CheckoutKeyInput{}
	return &this
}

// GetType returns the Type field value
func (o *CheckoutKeyInput) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CheckoutKeyInput) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CheckoutKeyInput) SetType(v string) {
	o.Type = v
}

func (o CheckoutKeyInput) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CheckoutKeyInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

type NullableCheckoutKeyInput struct {
	value *CheckoutKeyInput
	isSet bool
}

func (v NullableCheckoutKeyInput) Get() *CheckoutKeyInput {
	return v.value
}

func (v *NullableCheckoutKeyInput) Set(val *CheckoutKeyInput) {
	v.value = val
	v.isSet = true
}

func (v NullableCheckoutKeyInput) IsSet() bool {
	return v.isSet
}

func (v *NullableCheckoutKeyInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCheckoutKeyInput(val *CheckoutKeyInput) *NullableCheckoutKeyInput {
	return &NullableCheckoutKeyInput{value: val, isSet: true}
}

func (v NullableCheckoutKeyInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCheckoutKeyInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
