/*
CircleCI API

This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package circleci

import (
	"encoding/json"
)

// checks if the WebhookScope type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookScope{}

// WebhookScope The scope in which the relevant events that will trigger webhooks
type WebhookScope struct {
	// ID of the scope being used (at the moment, only project ID is supported)
	Id string `json:"id"`
	// Type of the scope being used
	Type string `json:"type"`
}

// NewWebhookScope instantiates a new WebhookScope object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookScope(id string, type_ string) *WebhookScope {
	this := WebhookScope{}
	this.Id = id
	this.Type = type_
	return &this
}

// NewWebhookScopeWithDefaults instantiates a new WebhookScope object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookScopeWithDefaults() *WebhookScope {
	this := WebhookScope{}
	return &this
}

// GetId returns the Id field value
func (o *WebhookScope) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *WebhookScope) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *WebhookScope) SetId(v string) {
	o.Id = v
}

// GetType returns the Type field value
func (o *WebhookScope) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *WebhookScope) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *WebhookScope) SetType(v string) {
	o.Type = v
}

func (o WebhookScope) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookScope) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

type NullableWebhookScope struct {
	value *WebhookScope
	isSet bool
}

func (v NullableWebhookScope) Get() *WebhookScope {
	return v.value
}

func (v *NullableWebhookScope) Set(val *WebhookScope) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookScope) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookScope) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookScope(val *WebhookScope) *NullableWebhookScope {
	return &NullableWebhookScope{value: val, isSet: true}
}

func (v NullableWebhookScope) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookScope) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
