/*
CircleCI API

This describes the resources that make up the CircleCI API v2.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->

API version: v2
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package circleci

import (
	"encoding/json"
	"time"
)

// checks if the ListEnvironmentVariablesFromContext200ResponseItemsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ListEnvironmentVariablesFromContext200ResponseItemsInner{}

// ListEnvironmentVariablesFromContext200ResponseItemsInner struct for ListEnvironmentVariablesFromContext200ResponseItemsInner
type ListEnvironmentVariablesFromContext200ResponseItemsInner struct {
	// The name of the environment variable
	Variable string `json:"variable"`
	// The date and time the environment variable was created.
	CreatedAt time.Time `json:"created_at"`
	// The date and time the environment variable was updated
	UpdatedAt time.Time `json:"updated_at"`
	// ID of the context (UUID)
	ContextId string `json:"context_id"`
}

// NewListEnvironmentVariablesFromContext200ResponseItemsInner instantiates a new ListEnvironmentVariablesFromContext200ResponseItemsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewListEnvironmentVariablesFromContext200ResponseItemsInner(variable string, createdAt time.Time, updatedAt time.Time, contextId string) *ListEnvironmentVariablesFromContext200ResponseItemsInner {
	this := ListEnvironmentVariablesFromContext200ResponseItemsInner{}
	this.Variable = variable
	this.CreatedAt = createdAt
	this.UpdatedAt = updatedAt
	this.ContextId = contextId
	return &this
}

// NewListEnvironmentVariablesFromContext200ResponseItemsInnerWithDefaults instantiates a new ListEnvironmentVariablesFromContext200ResponseItemsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewListEnvironmentVariablesFromContext200ResponseItemsInnerWithDefaults() *ListEnvironmentVariablesFromContext200ResponseItemsInner {
	this := ListEnvironmentVariablesFromContext200ResponseItemsInner{}
	return &this
}

// GetVariable returns the Variable field value
func (o *ListEnvironmentVariablesFromContext200ResponseItemsInner) GetVariable() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Variable
}

// GetVariableOk returns a tuple with the Variable field value
// and a boolean to check if the value has been set.
func (o *ListEnvironmentVariablesFromContext200ResponseItemsInner) GetVariableOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Variable, true
}

// SetVariable sets field value
func (o *ListEnvironmentVariablesFromContext200ResponseItemsInner) SetVariable(v string) {
	o.Variable = v
}

// GetCreatedAt returns the CreatedAt field value
func (o *ListEnvironmentVariablesFromContext200ResponseItemsInner) GetCreatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *ListEnvironmentVariablesFromContext200ResponseItemsInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *ListEnvironmentVariablesFromContext200ResponseItemsInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *ListEnvironmentVariablesFromContext200ResponseItemsInner) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *ListEnvironmentVariablesFromContext200ResponseItemsInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *ListEnvironmentVariablesFromContext200ResponseItemsInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetContextId returns the ContextId field value
func (o *ListEnvironmentVariablesFromContext200ResponseItemsInner) GetContextId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContextId
}

// GetContextIdOk returns a tuple with the ContextId field value
// and a boolean to check if the value has been set.
func (o *ListEnvironmentVariablesFromContext200ResponseItemsInner) GetContextIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContextId, true
}

// SetContextId sets field value
func (o *ListEnvironmentVariablesFromContext200ResponseItemsInner) SetContextId(v string) {
	o.ContextId = v
}

func (o ListEnvironmentVariablesFromContext200ResponseItemsInner) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ListEnvironmentVariablesFromContext200ResponseItemsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["variable"] = o.Variable
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["updated_at"] = o.UpdatedAt
	toSerialize["context_id"] = o.ContextId
	return toSerialize, nil
}

type NullableListEnvironmentVariablesFromContext200ResponseItemsInner struct {
	value *ListEnvironmentVariablesFromContext200ResponseItemsInner
	isSet bool
}

func (v NullableListEnvironmentVariablesFromContext200ResponseItemsInner) Get() *ListEnvironmentVariablesFromContext200ResponseItemsInner {
	return v.value
}

func (v *NullableListEnvironmentVariablesFromContext200ResponseItemsInner) Set(val *ListEnvironmentVariablesFromContext200ResponseItemsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableListEnvironmentVariablesFromContext200ResponseItemsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableListEnvironmentVariablesFromContext200ResponseItemsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableListEnvironmentVariablesFromContext200ResponseItemsInner(val *ListEnvironmentVariablesFromContext200ResponseItemsInner) *NullableListEnvironmentVariablesFromContext200ResponseItemsInner {
	return &NullableListEnvironmentVariablesFromContext200ResponseItemsInner{value: val, isSet: true}
}

func (v NullableListEnvironmentVariablesFromContext200ResponseItemsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableListEnvironmentVariablesFromContext200ResponseItemsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
