apiVersion: v1
kind: Secret
metadata:
  name: some-secret-1
type: Opaque
data:
  key1: dG9rZW4tdDAxCg==
  key2: dG9rZW4tdDAyCg==
  key3: dG9rZW4tdDAzCg==
  key4: dG9rZW4tdDA0Cg==
  key5: dG9rZW4tdDA1Cg==
